### ISSUE TITLE
Style injections not working for `Click here to install.`

### ISSUE THREAD

**Issue by adriandelgg** [catppuccin/vercel#4]
[Click here to install.](https://github.com/catppuccin/vercel/raw/main/catppuccin.user.css)
When you click into this it doesn't work and says:

`Stylus failed to parse usercss: variable @accentColour is undefined`

**Comment by ryanccn** [comment]
Fixed in https://github.com/catppuccin/vercel/commit/48d970c71d2f087dfe78137e014b547c5b6951d7, thank you for reporting this!
